language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION test Examples/compile

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2  

notifications:
  email: false
